apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-backend
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/maxxiAbhi/EKS-Test.git
    targetRevision: main
    path: backend

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated: {}  # optional: auto sync on git push
